name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: altenirm/deteao-de-animais:latest

jobs:
  buildar-docker-api:
    runs-on: ubuntu-latest
    environment: "Brazilian animais"   # 👈 aqui você linka o ambiente
    steps:
      - name: Check if secrets are loaded
        run: |
          if [ -z "${DOCKER_USERNAME}" ]; then
            echo "❌ Secret DOCKERHUB_USER não carregado"
            exit 1
          else
            echo "✅ Secret DOCKERHUB_USER carregado (mas mascarado nos logs)"
          fi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
